### ISSUE TITLE
Question: differences between this image and the official one

### ISSUE THREAD

**Issue by andoks** [haravich/fake-smtp-server#43]
I found this project when looking for a server to receive and display mails for testing, and through this I found mailcatcher. It seems like mailcather has "official" docker images though (https://hub.docker.com/r/sj26/mailcatcher/tags as mentioned in README: https://github.com/sj26/mailcatcher?tab=readme-ov-file#docker). Are there any reasons to use this project over the official images that may be worth knowing about?

**Comment by haravich** [comment]
True, the base image is updated every month in this repo and we use mailcatcher.
This repo also points to the mailcatcher https://github.com/haravich/fake-smtp-server?tab=readme-ov-file#credits
